export const products = [
  "pomidory",
  "pieczarki",
  "ser żółty",
  "ser feta",
  "ogórek",
  "kalafior",
  "marchewka",
  "śmietana",
  "kapusta kiszona",
  "bulion",
  "sól",
  "pieprz",
  "oliwa extra virgin",
  "liść laurowy",
  "ziele angielskie",
  "cebula",
  "mąka",
  "olej",
  "mięso mielone",
  "fix spaghetti bolognese knorr",
  "makaron spaghetti",
  "pomidory z puszki",
];
