export const recipes = [
  {
    id: 0,
    name: "Pomidory pieczone z fetą",
    ingredients: [
      "pomidory",
      "oregano",
      "sól",
      "pieprz",
      "ser feta",
      "oliwa extra virgin",
    ],
    link: "https://www.kwestiasmaku.com/przepis/pomidory-pieczone-z-feta",
  },
  {
    id: 1,
    name: "Kapusta z pieczarkami",
    ingredients: [
      "kapusta kiszona",
      "woda",
      "bulion",
      "liść lauroey",
      "ziele angielskie",
      "pieczarki",
      "cebula",
      "mąka",
      "olej roślinny",
      "sól",
      "pieprz",
    ],
    link: "https://www.kwestiasmaku.com/przepis/kapusta-z-pieczarkami",
  },
  {
    id: 2,
    name: "Spaghetti Bolognese",
    ingredients: [
      "mięso mielone",
      "fix spaghetti Bolognese Knorr",
      "makaron spaghetti",
      "pomidory z puszki",
      "olej",
      "woda",
    ],
    link: "https://www.przepisy.pl/przepis/spaghetti-bolognese-2",
  },
];
